// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

/**
 * @title VaultConfig
 * @dev Configuration library for Vault deployment
 * @notice This file is auto-generated from config/vaultConfig.json for network: hedera_mainnet
 * @notice Do not edit this file directly - edit config/vaultConfig.json and run: node config/genConfig.js hedera_mainnet
 */
library VaultConfig {
    // Current Network Configuration (hedera_mainnet)
    // Target Chain ID: 295
    // Target RPC URL: https://mainnet.hashio.io/api
    address constant TOKEN1 = address(0x000000000000000000000000000000000006f89a);
    address constant TOKEN2 = address(0x0000000000000000000000000000000000163B5a);
    uint256 constant MAX_SHAREHOLDERS = 50;
}
