import type { Metadata } from "next";
import "./globals.css";

import { exo, museoModerno } from "../lib/fonts";
import Navigator from "@/page/layout/navigator";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${exo.variable} ${museoModerno.variable} antialiased bg-black`}>
				<div className="flex items-center">
					<Navigator />
					{children}
				</div>
			</body>
		</html>
	);
}
