import type { Metadata } from "next";
import "./globals.css";

import { exo, museoModerno, quickSand } from "../lib/fonts";
import { NextIntlClientProvider } from "next-intl";
import ConditionalLayout from "@/components/layout/ConditionalLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${exo.variable} ${museoModerno.variable} ${quickSand.variable} antialiased bg-black text-white`}
			>
				<ConditionalLayout>
					<NextIntlClientProvider>{children}</NextIntlClientProvider>
				</ConditionalLayout>
			</body>
		</html>
	);
}

