import type { Metadata } from "next";
import "./globals.css";

import { exo, museoModerno, quickSan } from "../lib/fonts";
import Navigator from "@/page/layout/navigator";
import Header from "@/page/layout/header";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${exo.variable} ${museoModerno.variable} ${quickSan.variable} antialiased bg-black text-white`}>
				<div className="flex bg-gray-950 font-quicksand">
					<div className="w-[18%] border-r-2 border-black flex flex-col">
						<Navigator />
					</div>
					<div className="w-[82%] h-screen relative background-container">
						<Header />
						<div className="overflow-y-auto overflow-x-hidden h-[calc(100%-42px)] content">
							<NextIntlClientProvider>{children}</NextIntlClientProvider>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
