// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

/**
 * @title VaultConfig
 * @dev Configuration library for Vault deployment
 * @notice This file is auto-generated from config/vaultConfig.json for network: hedera_testnet
 * @notice Do not edit this file directly - edit config/vaultConfig.json and run: node config/genConfig.js hedera_testnet
 */
library VaultConfig {
    // Current Network Configuration (hedera_testnet)
    // Target Chain ID: 296
    // Target RPC URL: https://testnet.hashio.io/api
    address constant TOKEN1 = address(0x00000000000000000000000000000000007e35db);
    address constant TOKEN2 = address(0x992c980E9F6e76Ca231A20863e274B19dd792b3A);
    uint256 constant MAX_SHAREHOLDERS = 5;
}
